### ISSUE TITLE
フォルダ２つを統合する; code_it & code__it

### ISSUE THREAD

**Issue by yt-ysec** [yt-ysec/mahalo#26]
フォルダが２つになっちゃって、都合が悪いので、統合してmergeして、１つにするべき。

**Comment by yt-ysec** [comment]
1. md記法の
2. テスト
3. ほらできた。

**Comment by suraimu6872** [comment]
1. ローカルリポジトリからフォルダを削除
2. addする
3. pushする

**Comment by yt-ysec** [comment]
↑ いいけど、どのbranchでやる？

**Comment by rererenore1217** [comment]
git rm --cached [削除したいファイル]

**Comment by suraimu6872** [comment]
html_itブランチですか?

**Comment by keitosuwahara** [comment]
フォルダを削除したいとき

削除したいフォルダを開く
右端の・・・をクリックしてDelete directory をクリック
でどうですか？

**Comment by yt-ysec** [comment]
@suraimu6872 とすると、その後何かしないと、main に反映されませんね。

**Comment by suraimu6872** [comment]
4. prする
5. mergeする
でしょうか?

**Comment by iwagon99** [comment]
git rmをする

**Comment by yt-ysec** [comment]
では、それぞれの説を実際に試してみましょう。

**Comment by yt-ysec** [comment]
現時点では、prを使って削除や統合しましょう。
1. 新しいブランチを作り、
2. 統合作業して、
3. push - pr - merge
